export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  MERGE_MEMBER_TOO_FEW: "MERGE_MEMBER_TOO_FEW",
  MERGE_MEMBER_CONFLICT: "MERGE_MEMBER_CONFLICT",
  MERGE_GROUP_LOCKED: "MERGE_GROUP_LOCKED",
  MERGE_DRAFT_NOT_FOUND: "MERGE_DRAFT_NOT_FOUND",
  MERGE_ARCHIVED_READONLY: "MERGE_ARCHIVED_READONLY",
  MERGE_CROSS_DOCUMENT: "MERGE_CROSS_DOCUMENT"
} as const;

export type MergeErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
