export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  MERGE_SELECTION_TOO_SMALL: "MERGE_SELECTION_TOO_SMALL",
  MERGE_MEMBER_ARCHIVED: "MERGE_MEMBER_ARCHIVED",
  MERGE_RESULT_NOT_FOUND: "MERGE_RESULT_NOT_FOUND",
  MERGE_DRAFT_NOT_FOUND: "MERGE_DRAFT_NOT_FOUND"
} as const;
